/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package automatabuilder;

/**
 *
 * @author menegeps
 */
public class BuilderInterface extends javax.swing.JFrame {

    /**
     * Creates new form BuilderInterface
     */
    public BuilderInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboNoEstados = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        tfAlfabeto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfCadena = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Automata Builder  v1.0");
        setPreferredSize(new java.awt.Dimension(700, 500));
        setResizable(false);

        jLabel1.setText("No. de estados:");

        comboNoEstados.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        comboNoEstados.setToolTipText("Número de estados del autómata");
        comboNoEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNoEstadosActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel2.setText("∑:");

        tfAlfabeto.setToolTipText("Ingresa los simbolos del alfabeto separados por coma  (a,b,c)");
        tfAlfabeto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfAlfabetoFocusLost(evt);
            }
        });
        tfAlfabeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAlfabetoActionPerformed(evt);
            }
        });

        jLabel3.setText("Cadena:");

        tfCadena.setToolTipText("Ingresa la cadena que debera reconocer el autómata");
        tfCadena.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCadenaFocusLost(evt);
            }
        });
        tfCadena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCadenaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboNoEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfAlfabeto, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfCadena, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboNoEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(tfAlfabeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tfCadena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(359, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboNoEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNoEstadosActionPerformed
        System.out.println("Seleccionaste: "+comboNoEstados.getSelectedItem().toString());
    }//GEN-LAST:event_comboNoEstadosActionPerformed

    private void tfAlfabetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAlfabetoActionPerformed
        String []alfabeto1 = tfAlfabeto.getText().split(",");
        char [] alfabeto = new char[alfabeto1.length];
        int i =0;
        for (String c : alfabeto1) {            
            alfabeto[i++] = c.charAt(0);                        
        }
         for (int j = 0; j < alfabeto.length; j++) {
              System.out.println(alfabeto1[j]);
        }
        System.out.println("El alfabeto es: {"+tfAlfabeto.getText()+"}");
    }//GEN-LAST:event_tfAlfabetoActionPerformed

    private void tfCadenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCadenaActionPerformed
        System.out.println("La cadena a reconocer es: "+ tfCadena.getText());
    }//GEN-LAST:event_tfCadenaActionPerformed

    private void tfAlfabetoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfAlfabetoFocusLost
        System.out.println("El alfabeto es: {"+tfAlfabeto.getText()+"}");
    }//GEN-LAST:event_tfAlfabetoFocusLost

    private void tfCadenaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCadenaFocusLost
        System.out.println("La cadena a reconocer es: "+ tfCadena.getText());
    }//GEN-LAST:event_tfCadenaFocusLost

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboNoEstados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tfAlfabeto;
    private javax.swing.JTextField tfCadena;
    // End of variables declaration//GEN-END:variables
}
